# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
workflows:
  version: 2
  build-deploy:
    jobs:
      - DEV:
          filters:
            branches:
              only:
                - DEV
      - LOCAL:
          filters:
            branches:
              only:
                - LOCAL
jobs:
  DEV:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      cloudhubApplicationName: monolith-circleci-dev
    steps:
      - checkout
      - run:
          name: "Build Mule Application"
          command: "mvn deploy -DconnectedAppClientId=$connectedAppClientId -DconnectedAppClientSecret=$connectedAppClientSecret -DcloudhubEnvironment=$cloudhubEnvironment	-DmuleVersion=$muleVersion -DcloudhubWorkerType=$cloudhubWorkerType -DcloudhubApplicationName=$cloudhubApplicationName -DmuleDeploy"
  LOCAL:
    docker:
      - image: circleci/openjdk:8-jdk    
    environment:
      cloudhubApplicationName: monolith-circleci-LOCAL
    steps:
      - checkout
      - run:
          name: "Deploy Mule App"
          command: "mvn deploy -DconnectedAppClientId=$connectedAppClientId -DconnectedAppClientSecret=$connectedAppClientSecret -DcloudhubEnvironment=$cloudhubEnvironment	-DmuleVersion=$muleVersion -DcloudhubWorkerType=$cloudhubWorkerType -DcloudhubApplicationName=$cloudhubApplicationName -DmuleDeploy"
